package Apresentacao;

import java.util.ArrayList;
import java.util.Vector;
import Controle.*;
import Modelo.DisciplinaCursada;
import java.awt.event.ActionEvent;
import DAO.*;
import java.util.Iterator;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author david, beatriz
 */
public class InCadastroAluno extends javax.swing.JFrame {

    ArrayList<DisciplinaCursada> disciplinasCursadas = new ArrayList<DisciplinaCursada>();
    static ArrayList<DisciplinaCursada> disciplinas = DeserializaDisciplinas.deserializarDisciplinas();

    /**
     * Creates new form CadastroAluno
     */
    public InCadastroAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLnome = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jTcurso = new javax.swing.JTextField();
        jLcurso = new javax.swing.JLabel();
        jLmatricula = new javax.swing.JLabel();
        jTmatricula = new javax.swing.JTextField();
        jLsemestre = new javax.swing.JLabel();
        cbSemestre = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Acustica_e_vibracoes_veiculares = new javax.swing.JCheckBox();
        Analise_de_sinais_e_design_de_circuitos = new javax.swing.JCheckBox();
        Calculo1 = new javax.swing.JCheckBox();
        Calculo2 = new javax.swing.JCheckBox();
        Calculo3 = new javax.swing.JCheckBox();
        Circuitos_eletronicos1 = new javax.swing.JCheckBox();
        Circuito_Eletronico2 = new javax.swing.JCheckBox();
        circuitos_eletronicos3 = new javax.swing.JCheckBox();
        Comunicacoes_digitais_para_engenharia = new javax.swing.JCheckBox();
        Dinamica_de_veiculos = new javax.swing.JCheckBox();
        Dinamica_multicorpos_veicular = new javax.swing.JCheckBox();
        Eletricidade_aplicada = new javax.swing.JCheckBox();
        Eletronica_veicular = new javax.swing.JCheckBox();
        Equacoes_Diferenciais1 = new javax.swing.JCheckBox();
        Estrutura_de_dados_e_algoritimos = new javax.swing.JCheckBox();
        Fisica1 = new javax.swing.JCheckBox();
        Fundamentos_da_teoria_eletromagnetica = new javax.swing.JCheckBox();
        Fundamento_de_arquitetura_de_computadores = new javax.swing.JCheckBox();
        Fundamento_de_computiladores = new javax.swing.JCheckBox();
        Fundamento_de_rede_de_computadores = new javax.swing.JCheckBox();
        Fundamentos_de_sistemas_distribuidos = new javax.swing.JCheckBox();
        Fundamentos_de_sistemas_operacionais = new javax.swing.JCheckBox();
        Intrumentacao_eletronica = new javax.swing.JCheckBox();
        Introduca_a_Algebra_linear = new javax.swing.JCheckBox();
        Introducao_a_ciencia_da_computacao = new javax.swing.JCheckBox();
        Introducao_a_jogos_eletronicos = new javax.swing.JCheckBox();
        metodos_matematicos_para_engenharia = new javax.swing.JCheckBox();
        Metodos_numericos_para_engenharia = new javax.swing.JCheckBox();
        Microprocessadores_e_Microcompiladores = new javax.swing.JCheckBox();
        Orientacao_a_objetos = new javax.swing.JCheckBox();
        Principio_de_comunicacao = new javax.swing.JCheckBox();
        Processamento_de_sinais = new javax.swing.JCheckBox();
        Projeto_com_circuitos_reconfiguraveis1 = new javax.swing.JCheckBox();
        Projeto_de_circuitos_Reconfiguraveis2 = new javax.swing.JCheckBox();
        Projeto_de_microprocessadores = new javax.swing.JCheckBox();
        Sensores_e_transdutores = new javax.swing.JCheckBox();
        Sitemas_de_controladores = new javax.swing.JCheckBox();
        Sistemas_Digitais1 = new javax.swing.JCheckBox();
        Sistemas_Digitais2 = new javax.swing.JCheckBox();
        Sistemas_Embarcados = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jBsalvar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnTeste = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(8, 5, 2));

        jPanel2.setBackground(new java.awt.Color(169, 243, 132));

        jLnome.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLnome.setForeground(new java.awt.Color(254, 254, 254));
        jLnome.setText("Nome");

        jLcurso.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLcurso.setForeground(new java.awt.Color(255, 250, 250));
        jLcurso.setText("Curso");

        jLmatricula.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLmatricula.setForeground(new java.awt.Color(251, 249, 249));
        jLmatricula.setText("Matricula");

        jLsemestre.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLsemestre.setForeground(new java.awt.Color(252, 245, 245));
        jLsemestre.setText("Semestre");

        cbSemestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  "1º", "2º", "3º", "4º", "5º", "6º", "7º", "8º", "9º", "10º"}));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Matérias Cursadas"));

        jPanel1.setBackground(new java.awt.Color(94, 36, 211));
        jPanel1.setForeground(new java.awt.Color(255, 250, 250));

        Acustica_e_vibracoes_veiculares.setBackground(new java.awt.Color(94, 32, 211));
        Acustica_e_vibracoes_veiculares.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Acustica_e_vibracoes_veiculares.setForeground(new java.awt.Color(254, 242, 242));
        Acustica_e_vibracoes_veiculares.setText("Acustica e Vibracoes Veiculares");

        Analise_de_sinais_e_design_de_circuitos.setBackground(new java.awt.Color(94, 36, 211));
        Analise_de_sinais_e_design_de_circuitos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Analise_de_sinais_e_design_de_circuitos.setForeground(new java.awt.Color(255, 245, 245));
        Analise_de_sinais_e_design_de_circuitos.setText("Analise de Sinais e Design de circuitos ");
        Analise_de_sinais_e_design_de_circuitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Analise_de_sinais_e_design_de_circuitosActionPerformed(evt);
            }
        });

        Calculo1.setBackground(new java.awt.Color(94, 36, 211));
        Calculo1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Calculo1.setForeground(new java.awt.Color(254, 242, 242));
        Calculo1.setText("Calculo 1");

        Calculo2.setBackground(new java.awt.Color(94, 36, 211));
        Calculo2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Calculo2.setForeground(new java.awt.Color(254, 242, 242));
        Calculo2.setText("Calculo 2");

        Calculo3.setBackground(new java.awt.Color(94, 36, 211));
        Calculo3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Calculo3.setForeground(new java.awt.Color(249, 239, 239));
        Calculo3.setText("Calculo 3");

        Circuitos_eletronicos1.setBackground(new java.awt.Color(94, 36, 211));
        Circuitos_eletronicos1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Circuitos_eletronicos1.setForeground(new java.awt.Color(249, 239, 239));
        Circuitos_eletronicos1.setText("Circuitos Eletronicos 1");

        Circuito_Eletronico2.setBackground(new java.awt.Color(94, 36, 211));
        Circuito_Eletronico2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Circuito_Eletronico2.setForeground(new java.awt.Color(249, 239, 239));
        Circuito_Eletronico2.setText("Circuitos Eletronicos 2");

        circuitos_eletronicos3.setBackground(new java.awt.Color(94, 36, 211));
        circuitos_eletronicos3.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        circuitos_eletronicos3.setForeground(new java.awt.Color(255, 250, 250));
        circuitos_eletronicos3.setText("Circuitos Eletronicos 3");

        Comunicacoes_digitais_para_engenharia.setBackground(new java.awt.Color(94, 36, 211));
        Comunicacoes_digitais_para_engenharia.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Comunicacoes_digitais_para_engenharia.setForeground(new java.awt.Color(255, 250, 250));
        Comunicacoes_digitais_para_engenharia.setText("Comunicacoes Digitais Para Engenharia");

        Dinamica_de_veiculos.setBackground(new java.awt.Color(94, 36, 211));
        Dinamica_de_veiculos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Dinamica_de_veiculos.setForeground(new java.awt.Color(255, 250, 250));
        Dinamica_de_veiculos.setText("Dinamica De Veiculos");

        Dinamica_multicorpos_veicular.setBackground(new java.awt.Color(94, 36, 211));
        Dinamica_multicorpos_veicular.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Dinamica_multicorpos_veicular.setForeground(new java.awt.Color(255, 250, 250));
        Dinamica_multicorpos_veicular.setText("Dinâmica Multicorpos Veicular");
        Dinamica_multicorpos_veicular.setActionCommand("Dinamica Multicorpos Veicular");

        Eletricidade_aplicada.setBackground(new java.awt.Color(94, 36, 211));
        Eletricidade_aplicada.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Eletricidade_aplicada.setForeground(new java.awt.Color(251, 249, 249));
        Eletricidade_aplicada.setText("Eletricidade Aplicada");

        Eletronica_veicular.setBackground(new java.awt.Color(94, 36, 211));
        Eletronica_veicular.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Eletronica_veicular.setForeground(new java.awt.Color(251, 249, 249));
        Eletronica_veicular.setText("Eletrônica Veicular");

        Equacoes_Diferenciais1.setBackground(new java.awt.Color(94, 36, 211));
        Equacoes_Diferenciais1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Equacoes_Diferenciais1.setForeground(new java.awt.Color(251, 249, 249));
        Equacoes_Diferenciais1.setText("Equações Diferenciais 1");

        Estrutura_de_dados_e_algoritimos.setBackground(new java.awt.Color(94, 36, 211));
        Estrutura_de_dados_e_algoritimos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Estrutura_de_dados_e_algoritimos.setForeground(new java.awt.Color(251, 249, 249));
        Estrutura_de_dados_e_algoritimos.setText("Estrutura de Dados e Algoritimos");

        Fisica1.setBackground(new java.awt.Color(94, 36, 211));
        Fisica1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Fisica1.setForeground(new java.awt.Color(251, 249, 249));
        Fisica1.setText("Física 1");

        Fundamentos_da_teoria_eletromagnetica.setBackground(new java.awt.Color(94, 36, 211));
        Fundamentos_da_teoria_eletromagnetica.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Fundamentos_da_teoria_eletromagnetica.setForeground(new java.awt.Color(254, 254, 254));
        Fundamentos_da_teoria_eletromagnetica.setText("Fundamentos da teoria Eletromagnética");

        Fundamento_de_arquitetura_de_computadores.setBackground(new java.awt.Color(94, 36, 211));
        Fundamento_de_arquitetura_de_computadores.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Fundamento_de_arquitetura_de_computadores.setForeground(new java.awt.Color(254, 254, 254));
        Fundamento_de_arquitetura_de_computadores.setText("Fundamento de Arquitetura de Computadores");

        Fundamento_de_computiladores.setBackground(new java.awt.Color(94, 36, 211));
        Fundamento_de_computiladores.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Fundamento_de_computiladores.setForeground(new java.awt.Color(254, 254, 254));
        Fundamento_de_computiladores.setText("Fundamento de Compiladores");

        Fundamento_de_rede_de_computadores.setBackground(new java.awt.Color(94, 36, 211));
        Fundamento_de_rede_de_computadores.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Fundamento_de_rede_de_computadores.setForeground(new java.awt.Color(254, 254, 254));
        Fundamento_de_rede_de_computadores.setText("Fundamento de Redes de Computadores");

        Fundamentos_de_sistemas_distribuidos.setBackground(new java.awt.Color(94, 36, 211));
        Fundamentos_de_sistemas_distribuidos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Fundamentos_de_sistemas_distribuidos.setForeground(new java.awt.Color(254, 254, 254));
        Fundamentos_de_sistemas_distribuidos.setText("Fundamentos de Sistemas Distribuídos");

        Fundamentos_de_sistemas_operacionais.setBackground(new java.awt.Color(94, 36, 211));
        Fundamentos_de_sistemas_operacionais.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Fundamentos_de_sistemas_operacionais.setForeground(new java.awt.Color(254, 254, 254));
        Fundamentos_de_sistemas_operacionais.setText("Fundamentos de Sistemas Operacionais");

        Intrumentacao_eletronica.setBackground(new java.awt.Color(94, 36, 211));
        Intrumentacao_eletronica.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Intrumentacao_eletronica.setForeground(new java.awt.Color(254, 254, 254));
        Intrumentacao_eletronica.setText("Instrumentação Eletrônica");

        Introduca_a_Algebra_linear.setBackground(new java.awt.Color(94, 36, 211));
        Introduca_a_Algebra_linear.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Introduca_a_Algebra_linear.setForeground(new java.awt.Color(254, 254, 254));
        Introduca_a_Algebra_linear.setText("Introdução a Algebra Linear");

        Introducao_a_ciencia_da_computacao.setBackground(new java.awt.Color(94, 36, 211));
        Introducao_a_ciencia_da_computacao.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Introducao_a_ciencia_da_computacao.setForeground(new java.awt.Color(254, 254, 254));
        Introducao_a_ciencia_da_computacao.setText("Introdução a Ciência da Computação");

        Introducao_a_jogos_eletronicos.setBackground(new java.awt.Color(94, 36, 211));
        Introducao_a_jogos_eletronicos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Introducao_a_jogos_eletronicos.setForeground(new java.awt.Color(254, 254, 254));
        Introducao_a_jogos_eletronicos.setText("Introdução a Jogos Eletrônicos");

        metodos_matematicos_para_engenharia.setBackground(new java.awt.Color(94, 36, 211));
        metodos_matematicos_para_engenharia.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        metodos_matematicos_para_engenharia.setForeground(new java.awt.Color(254, 254, 254));
        metodos_matematicos_para_engenharia.setText("Métodos Matemáticos para Engenharia ");

        Metodos_numericos_para_engenharia.setBackground(new java.awt.Color(94, 36, 211));
        Metodos_numericos_para_engenharia.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Metodos_numericos_para_engenharia.setForeground(new java.awt.Color(254, 254, 254));
        Metodos_numericos_para_engenharia.setText("Métodos Numericos para Engenharia");

        Microprocessadores_e_Microcompiladores.setBackground(new java.awt.Color(94, 36, 211));
        Microprocessadores_e_Microcompiladores.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Microprocessadores_e_Microcompiladores.setForeground(new java.awt.Color(254, 254, 254));
        Microprocessadores_e_Microcompiladores.setText("Microprocessadores e Microcompiladores");

        Orientacao_a_objetos.setBackground(new java.awt.Color(94, 36, 211));
        Orientacao_a_objetos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Orientacao_a_objetos.setForeground(new java.awt.Color(254, 254, 254));
        Orientacao_a_objetos.setText("Orientação a Objetos");

        Principio_de_comunicacao.setBackground(new java.awt.Color(94, 36, 211));
        Principio_de_comunicacao.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Principio_de_comunicacao.setForeground(new java.awt.Color(254, 254, 254));
        Principio_de_comunicacao.setText("Princípios de Comunicação");

        Processamento_de_sinais.setBackground(new java.awt.Color(94, 36, 211));
        Processamento_de_sinais.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Processamento_de_sinais.setForeground(new java.awt.Color(254, 254, 254));
        Processamento_de_sinais.setText("Processamento de Sinais");

        Projeto_com_circuitos_reconfiguraveis1.setBackground(new java.awt.Color(94, 36, 211));
        Projeto_com_circuitos_reconfiguraveis1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Projeto_com_circuitos_reconfiguraveis1.setForeground(new java.awt.Color(254, 254, 254));
        Projeto_com_circuitos_reconfiguraveis1.setText("Projeto com Circuitos Reconfiguráveis 1");

        Projeto_de_circuitos_Reconfiguraveis2.setBackground(new java.awt.Color(94, 36, 211));
        Projeto_de_circuitos_Reconfiguraveis2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Projeto_de_circuitos_Reconfiguraveis2.setForeground(new java.awt.Color(254, 254, 254));
        Projeto_de_circuitos_Reconfiguraveis2.setText("Projeto com Circuitos Reconfiguráveis 2");

        Projeto_de_microprocessadores.setBackground(new java.awt.Color(94, 36, 211));
        Projeto_de_microprocessadores.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Projeto_de_microprocessadores.setForeground(new java.awt.Color(254, 254, 254));
        Projeto_de_microprocessadores.setText("Projeto de Microprocessadores");

        Sensores_e_transdutores.setBackground(new java.awt.Color(94, 36, 211));
        Sensores_e_transdutores.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Sensores_e_transdutores.setForeground(new java.awt.Color(254, 254, 254));
        Sensores_e_transdutores.setText("Sensores e Transdutores ");

        Sitemas_de_controladores.setBackground(new java.awt.Color(94, 36, 211));
        Sitemas_de_controladores.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Sitemas_de_controladores.setForeground(new java.awt.Color(254, 254, 254));
        Sitemas_de_controladores.setText("Sistemas de Controles");

        Sistemas_Digitais1.setBackground(new java.awt.Color(94, 36, 211));
        Sistemas_Digitais1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Sistemas_Digitais1.setForeground(new java.awt.Color(254, 254, 254));
        Sistemas_Digitais1.setText("Sistemas Digitais 1");

        Sistemas_Digitais2.setBackground(new java.awt.Color(94, 36, 211));
        Sistemas_Digitais2.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Sistemas_Digitais2.setForeground(new java.awt.Color(254, 254, 254));
        Sistemas_Digitais2.setText("Sistemas Digitais 2");

        Sistemas_Embarcados.setBackground(new java.awt.Color(94, 36, 211));
        Sistemas_Embarcados.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Sistemas_Embarcados.setForeground(new java.awt.Color(254, 254, 254));
        Sistemas_Embarcados.setText("Sistemas Embarcados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Acustica_e_vibracoes_veiculares)
                    .addComponent(Analise_de_sinais_e_design_de_circuitos)
                    .addComponent(Calculo1)
                    .addComponent(Calculo2)
                    .addComponent(Calculo3)
                    .addComponent(Circuitos_eletronicos1)
                    .addComponent(Circuito_Eletronico2)
                    .addComponent(circuitos_eletronicos3)
                    .addComponent(Comunicacoes_digitais_para_engenharia)
                    .addComponent(Dinamica_de_veiculos)
                    .addComponent(Dinamica_multicorpos_veicular)
                    .addComponent(Eletricidade_aplicada)
                    .addComponent(Eletronica_veicular)
                    .addComponent(Equacoes_Diferenciais1)
                    .addComponent(Estrutura_de_dados_e_algoritimos)
                    .addComponent(Fisica1)
                    .addComponent(Fundamentos_da_teoria_eletromagnetica)
                    .addComponent(Fundamento_de_arquitetura_de_computadores)
                    .addComponent(Fundamento_de_computiladores)
                    .addComponent(Fundamento_de_rede_de_computadores)
                    .addComponent(Fundamentos_de_sistemas_distribuidos)
                    .addComponent(Fundamentos_de_sistemas_operacionais)
                    .addComponent(Intrumentacao_eletronica)
                    .addComponent(Introduca_a_Algebra_linear)
                    .addComponent(Introducao_a_jogos_eletronicos)
                    .addComponent(metodos_matematicos_para_engenharia)
                    .addComponent(Metodos_numericos_para_engenharia)
                    .addComponent(Microprocessadores_e_Microcompiladores)
                    .addComponent(Orientacao_a_objetos)
                    .addComponent(Principio_de_comunicacao)
                    .addComponent(Processamento_de_sinais)
                    .addComponent(Projeto_com_circuitos_reconfiguraveis1)
                    .addComponent(Projeto_de_circuitos_Reconfiguraveis2)
                    .addComponent(Projeto_de_microprocessadores)
                    .addComponent(Sensores_e_transdutores)
                    .addComponent(Introducao_a_ciencia_da_computacao)
                    .addComponent(Sitemas_de_controladores)
                    .addComponent(Sistemas_Digitais1)
                    .addComponent(Sistemas_Digitais2)
                    .addComponent(Sistemas_Embarcados, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Acustica_e_vibracoes_veiculares)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Analise_de_sinais_e_design_de_circuitos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calculo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calculo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Calculo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Circuitos_eletronicos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Circuito_Eletronico2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(circuitos_eletronicos3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Comunicacoes_digitais_para_engenharia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dinamica_de_veiculos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Dinamica_multicorpos_veicular, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Eletricidade_aplicada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Eletronica_veicular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Equacoes_Diferenciais1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Estrutura_de_dados_e_algoritimos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fisica1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fundamentos_da_teoria_eletromagnetica, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fundamento_de_arquitetura_de_computadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fundamento_de_computiladores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fundamento_de_rede_de_computadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Fundamentos_de_sistemas_distribuidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fundamentos_de_sistemas_operacionais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Intrumentacao_eletronica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Introduca_a_Algebra_linear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Introducao_a_ciencia_da_computacao)
                .addGap(3, 3, 3)
                .addComponent(Introducao_a_jogos_eletronicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(metodos_matematicos_para_engenharia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Metodos_numericos_para_engenharia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Microprocessadores_e_Microcompiladores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Orientacao_a_objetos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Principio_de_comunicacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Processamento_de_sinais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Projeto_com_circuitos_reconfiguraveis1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Projeto_de_circuitos_Reconfiguraveis2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Projeto_de_microprocessadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sensores_e_transdutores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sitemas_de_controladores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sistemas_Digitais1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sistemas_Digitais2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sistemas_Embarcados)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 19, 136));
        jLabel1.setText("Cadastro");

        jBsalvar.setBackground(new java.awt.Color(60, 2, 159));
        jBsalvar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jBsalvar.setForeground(new java.awt.Color(254, 254, 254));
        jBsalvar.setText("Salvar");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        btnTeste.setText("Teste");
        btnTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addComponent(jLabel1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLmatricula)
                    .addComponent(jLsemestre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jSeparator4)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLcurso)
                            .addComponent(jLnome))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnTeste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnome)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcurso)
                    .addComponent(jTcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLmatricula)
                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLsemestre)
                    .addComponent(cbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeste))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        String nome = jTnome.getText();
        String matricula = jTmatricula.getText();
        String curso = jTcurso.getText();
        String semestre = cbSemestre.getSelectedItem().toString();
        ControlaAluno controle = new ControlaAluno();
        controle.CadastraAluno(nome, matricula, curso, semestre);
        controle.chamaSerializar();
        
        verifica(Acustica_e_vibracoes_veiculares);
        verifica(Analise_de_sinais_e_design_de_circuitos);
        verifica(Calculo1);
        verifica(Calculo2);
        verifica(Calculo3);
        verifica(Circuitos_eletronicos1);
        verifica(Circuito_Eletronico2);
        verifica(circuitos_eletronicos3);
        verifica(Comunicacoes_digitais_para_engenharia);
        verifica(Dinamica_de_veiculos);

        //Chamar método que gera XML
        XmlDisciplinasCursadas.gerarXml(disciplinasCursadas);

        //Visualizar dados da array, apenas para teste
        JOptionPane.showMessageDialog(null, "\nNome: " + nome + "\nMatrícula: " + matricula + "\nCurso: " + curso + "\nSemestre: " + semestre + "\n" + disciplinasCursadas);
        this.dispose();
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void btnTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesteActionPerformed
        jTnome.setText("Teste");
        jTcurso.setText("Curso");
        jTmatricula.setText("110035467");
        cbSemestre.setSelectedIndex(7);
        Calculo1.setSelected(true);
        Calculo2.setSelected(true);
        Acustica_e_vibracoes_veiculares.setSelected(true);
        Circuitos_eletronicos1.setSelected(true);
        
    }//GEN-LAST:event_btnTesteActionPerformed

    private void Analise_de_sinais_e_design_de_circuitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Analise_de_sinais_e_design_de_circuitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Analise_de_sinais_e_design_de_circuitosActionPerformed

    public void verifica(JCheckBox cb) {

        DisciplinaCursada dp = new DisciplinaCursada();
        
        if (cb.isSelected()) {
            for (DisciplinaCursada dc : disciplinas) {
                if (dc.getNome().equalsIgnoreCase(cb.getText())) {
                    dp = new DisciplinaCursada(cb.getText(), dc.getCodigo(), dc.getCod_preReq());
                }
            }
            disciplinasCursadas.add(dp);
        }
        if (!cb.isSelected()) {

            for (Iterator<DisciplinaCursada> it = disciplinasCursadas.iterator(); it.hasNext();) {
                DisciplinaCursada n = it.next();
                if (cb.getText().contains(n.getNome())) {
                    it.remove();
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InCadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        InCadastroAluno cadastro = new InCadastroAluno();
        cadastro.setVisible(true);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InCadastroAluno().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Acustica_e_vibracoes_veiculares;
    private javax.swing.JCheckBox Analise_de_sinais_e_design_de_circuitos;
    private javax.swing.JCheckBox Calculo1;
    private javax.swing.JCheckBox Calculo2;
    private javax.swing.JCheckBox Calculo3;
    private javax.swing.JCheckBox Circuito_Eletronico2;
    private javax.swing.JCheckBox Circuitos_eletronicos1;
    private javax.swing.JCheckBox Comunicacoes_digitais_para_engenharia;
    private javax.swing.JCheckBox Dinamica_de_veiculos;
    private javax.swing.JCheckBox Dinamica_multicorpos_veicular;
    private javax.swing.JCheckBox Eletricidade_aplicada;
    private javax.swing.JCheckBox Eletronica_veicular;
    private javax.swing.JCheckBox Equacoes_Diferenciais1;
    private javax.swing.JCheckBox Estrutura_de_dados_e_algoritimos;
    private javax.swing.JCheckBox Fisica1;
    private javax.swing.JCheckBox Fundamento_de_arquitetura_de_computadores;
    private javax.swing.JCheckBox Fundamento_de_computiladores;
    private javax.swing.JCheckBox Fundamento_de_rede_de_computadores;
    private javax.swing.JCheckBox Fundamentos_da_teoria_eletromagnetica;
    private javax.swing.JCheckBox Fundamentos_de_sistemas_distribuidos;
    private javax.swing.JCheckBox Fundamentos_de_sistemas_operacionais;
    private javax.swing.JCheckBox Introduca_a_Algebra_linear;
    private javax.swing.JCheckBox Introducao_a_ciencia_da_computacao;
    private javax.swing.JCheckBox Introducao_a_jogos_eletronicos;
    private javax.swing.JCheckBox Intrumentacao_eletronica;
    private javax.swing.JCheckBox Metodos_numericos_para_engenharia;
    private javax.swing.JCheckBox Microprocessadores_e_Microcompiladores;
    private javax.swing.JCheckBox Orientacao_a_objetos;
    private javax.swing.JCheckBox Principio_de_comunicacao;
    private javax.swing.JCheckBox Processamento_de_sinais;
    private javax.swing.JCheckBox Projeto_com_circuitos_reconfiguraveis1;
    private javax.swing.JCheckBox Projeto_de_circuitos_Reconfiguraveis2;
    private javax.swing.JCheckBox Projeto_de_microprocessadores;
    private javax.swing.JCheckBox Sensores_e_transdutores;
    private javax.swing.JCheckBox Sistemas_Digitais1;
    private javax.swing.JCheckBox Sistemas_Digitais2;
    private javax.swing.JCheckBox Sistemas_Embarcados;
    private javax.swing.JCheckBox Sitemas_de_controladores;
    private javax.swing.JButton btnTeste;
    private javax.swing.JComboBox cbSemestre;
    private javax.swing.JCheckBox circuitos_eletronicos3;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLcurso;
    private javax.swing.JLabel jLmatricula;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLsemestre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField jTcurso;
    public javax.swing.JTextField jTmatricula;
    public javax.swing.JTextField jTnome;
    private javax.swing.JCheckBox metodos_matematicos_para_engenharia;
    // End of variables declaration//GEN-END:variables
}
