package Apresentacao;

import java.util.ArrayList;
import java.util.Vector;
import Controle.*;
import Modelo.DisciplinaCursada;
import Modelo.Disciplinas.*;
import java.awt.event.ActionEvent;
import DAO.*;
import java.util.Iterator;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import Controle.Disciplinas.*;
import javax.swing.JComponent;

/**
 *
 * @author david, beatriz
 */
public class InDadosAluno extends javax.swing.JFrame {

    private ArrayList<DisciplinaCursada> listDisciplinasCursadas = new ArrayList<DisciplinaCursada>();
    private static ArrayList<DisciplinaCursada> listTodasDisciplinas = DeserializaDisciplinas.deserializarDisciplinas();

    /**
     * Creates new form CadastroAluno
     */
    public InDadosAluno() {
        initComponents();
        //this.gerarJComboBox();
    }

    public void addJComboBox(ArrayList<JCheckBox> listCheckBox) {
        for (int i = 0; i < listCheckBox.size(); i++) {
            this.jPanel1.add(listCheckBox.get(i));
        }
    }

    public void setDados(String nome, String matricula, String curso, String semestre, ArrayList<DisciplinaCursada> disciplinas) {
        this.setDadosAluno(nome, matricula, curso, semestre);
        this.setDisciplinas(disciplinas);
    }

    private void setDisciplinas(ArrayList<DisciplinaCursada> listDisciplinasCursadas) {
        Iterator<DisciplinaCursada> iDisciplinasCursadas = listDisciplinasCursadas.iterator();
        while (iDisciplinasCursadas.hasNext()) {
            DisciplinaCursada obDisciplinaCursada = iDisciplinasCursadas.next();
            this.markJCheckBox(obDisciplinaCursada.getNome());

        }
    }

    private void markJCheckBox(String nomeDisciplinas) {
        for (int i = 0; i < this.jPanel1.getComponentCount(); i++) {
            JComponent obJComponent = (JComponent) this.jPanel1.getComponent(i);
            if (obJComponent instanceof JCheckBox) {
                JCheckBox obJCheckBox = (JCheckBox) obJComponent;
                System.out.println("a disciplina " + nomeDisciplinas);
                if (obJCheckBox.getText().equals(nomeDisciplinas)) {
                    obJCheckBox.setSelected(true);
                }
            }
        }
    }

    private ArrayList<DisciplinaCursada> gerarListDisciplinasCursadas() {
        ArrayList<DisciplinaCursada> listDisciplinasCursadas = new ArrayList<DisciplinaCursada>();
        for (int i = 0; i < this.jPanel1.getComponentCount(); i++) {
            JComponent obJComponent = (JComponent) this.jPanel1.getComponent(i);
            if (obJComponent instanceof JCheckBox) {
                JCheckBox obJCheckBox = (JCheckBox) obJComponent;
                if (obJCheckBox.isSelected() == true) {
                    try {
                        listDisciplinasCursadas.add(this.getDisciplina(obJCheckBox.getText()));
                    } catch (NullPointerException ex) {
                    }
                }
            }
        }
        return listDisciplinasCursadas;
    }

    private void setDadosAluno(String nome, String matricula, String curso, String semestre) {
        this.jTnome.setText(nome);
        this.jTmatricula.setText(matricula);
        this.jTcurso.setText(curso);
        this.cbSemestre.setSelectedItem(semestre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLnome = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jTcurso = new javax.swing.JTextField();
        jLcurso = new javax.swing.JLabel();
        jLmatricula = new javax.swing.JLabel();
        jTmatricula = new javax.swing.JTextField();
        jLsemestre = new javax.swing.JLabel();
        cbSemestre = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jBsalvar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnTeste = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(8, 5, 2));

        jPanel2.setBackground(new java.awt.Color(169, 243, 132));

        jLnome.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLnome.setForeground(new java.awt.Color(254, 254, 254));
        jLnome.setText("Nome");

        jLcurso.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLcurso.setForeground(new java.awt.Color(255, 250, 250));
        jLcurso.setText("Curso");

        jLmatricula.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLmatricula.setForeground(new java.awt.Color(251, 249, 249));
        jLmatricula.setText("Matricula");

        jLsemestre.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLsemestre.setForeground(new java.awt.Color(252, 245, 245));
        jLsemestre.setText("Semestre");

        cbSemestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  "1º", "2º", "3º", "4º", "5º", "6º", "7º", "8º", "9º", "10º"}));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Matérias Cursadas"));

        jPanel1.setBackground(new java.awt.Color(94, 36, 211));
        jPanel1.setForeground(new java.awt.Color(255, 250, 250));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1334, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(65, 19, 136));
        jLabel1.setText("Cadastro");

        jBsalvar.setBackground(new java.awt.Color(60, 2, 159));
        jBsalvar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jBsalvar.setForeground(new java.awt.Color(254, 254, 254));
        jBsalvar.setText("Salvar");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        btnTeste.setText("Teste");
        btnTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addComponent(jLabel1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLmatricula)
                    .addComponent(jLsemestre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLcurso)
                            .addComponent(jLnome))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnTeste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addGap(9, 9, 9))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLnome)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcurso)
                    .addComponent(jTcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLmatricula)
                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLsemestre)
                    .addComponent(cbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeste))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        String nome = jTnome.getText();
        String matricula = jTmatricula.getText();
        String curso = jTcurso.getText();
        String semestre = cbSemestre.getSelectedItem().toString();
        ControleAluno controle = new ControleAluno();
        try{
            controle.CadastraAluno(nome, matricula, curso, semestre,this.gerarListDisciplinasCursadas());
            controle.chamaSerializar();
            this.dispose();
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void btnTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesteActionPerformed
        jTnome.setText("Teste");
        jTcurso.setText("Curso");
        jTmatricula.setText("110035467");
        cbSemestre.setSelectedIndex(7);


    }//GEN-LAST:event_btnTesteActionPerformed

    /**
     * Encontrar disciplina na lista
     *
     * @param nmDisciplina nome da disciplina desejada
     * @return objeto DisciplinaCursada
     */
    private DisciplinaCursada getDisciplina(String nmDisciplina) {
        DisciplinaCursada obDisciplinaCursada = null;
        for (DisciplinaCursada obProvDiscplinaCursada : listTodasDisciplinas) {
            if (obProvDiscplinaCursada.getNome().equalsIgnoreCase(nmDisciplina)) {
                obDisciplinaCursada = obProvDiscplinaCursada;
            }
        }
        if (obDisciplinaCursada == null) {
            throw new NullPointerException();
        }
        return obDisciplinaCursada;
    }

    private void addDisciplina(String nmDisciplina) {
        try {
            listDisciplinasCursadas.add(this.getDisciplina(nmDisciplina));
        } catch (NullPointerException ex) {
            //nao faz nada
        }
    }

    private void rmDisciplina(String nmDisciplina) {
        try {
            listDisciplinasCursadas.remove(this.getDisciplina(nmDisciplina));
        } catch (NullPointerException ex) {
            //nao faz nada
        }

    }

    public void actionCheckBox(JCheckBox cb) {
        if (cb.isSelected()) {
            this.addDisciplina(cb.getText());
        }
        if (!cb.isSelected()) {
            this.rmDisciplina(cb.getText());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTeste;
    private javax.swing.JComboBox cbSemestre;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLcurso;
    private javax.swing.JLabel jLmatricula;
    private javax.swing.JLabel jLnome;
    private javax.swing.JLabel jLsemestre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField jTcurso;
    public javax.swing.JTextField jTmatricula;
    public javax.swing.JTextField jTnome;
    // End of variables declaration//GEN-END:variables
}
