package Apresentacao;

import Controle.ControleAluno;
import Controle.ControlePdf;
import DAO.DeserializaAluno;

/**
 *
 * @author David, Felipe
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBpdf = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBAluno = new javax.swing.JButton();
        jBgrade = new javax.swing.JButton();
        jBVisualizaGrade = new javax.swing.JButton();
        jBDisciplinas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLUniversidadeBrasilia = new javax.swing.JLabel();
        jLUnBimg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(169, 243, 132));

        jBpdf.setBackground(new java.awt.Color(60, 2, 159));
        jBpdf.setForeground(new java.awt.Color(254, 254, 254));
        jBpdf.setText("PDF");
        jBpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpdfActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(57, 2, 126));

        jBAluno.setBackground(new java.awt.Color(1, 176, 13));
        jBAluno.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jBAluno.setForeground(new java.awt.Color(254, 254, 254));
        jBAluno.setText("Aluno");
        jBAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlunoActionPerformed(evt);
            }
        });

        jBgrade.setBackground(new java.awt.Color(1, 176, 13));
        jBgrade.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jBgrade.setForeground(new java.awt.Color(254, 254, 254));
        jBgrade.setText("Grade");
        jBgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgradeActionPerformed(evt);
            }
        });
        jBgrade.setEnabled(false);

        jBVisualizaGrade.setBackground(new java.awt.Color(1, 176, 13));
        jBVisualizaGrade.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jBVisualizaGrade.setForeground(new java.awt.Color(254, 254, 254));
        jBVisualizaGrade.setText("Visualizar Grade");
        jBVisualizaGrade.setEnabled(false);

        jBDisciplinas.setBackground(new java.awt.Color(1, 176, 13));
        jBDisciplinas.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jBDisciplinas.setForeground(new java.awt.Color(254, 254, 254));
        jBDisciplinas.setText("Disciplinas");
        jBDisciplinas.setEnabled(true);
        jBDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDisciplinasActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(57, 2, 126));

        jSeparator3.setBackground(new java.awt.Color(57, 2, 126));

        jLUniversidadeBrasilia.setText("Universidade de Brasilia");

        jLUnBimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/unb_logo2.gif"))); // NOI18N
        jLUnBimg.setText("jLabel2");
        jLUnBimg.setMinimumSize(new java.awt.Dimension(350, 100));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(65, 19, 136));
        jLabel2.setText("sisGHE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLUniversidadeBrasilia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBpdf))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jBAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jBVisualizaGrade)
                        .addGap(28, 28, 28)
                        .addComponent(jBDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLUnBimg, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVisualizaGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLUnBimg, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBpdf)
                    .addComponent(jLUniversidadeBrasilia)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpdfActionPerformed

        ControlePdf controle = new ControlePdf();
        controle.chamaDeserializar();// puxa e valida os dados do XML (ainda nao funcionando)
        controle.build();// inicia construção do arquivo

    }//GEN-LAST:event_jBpdfActionPerformed

    private void jBAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlunoActionPerformed
      
         ControleAluno controle = new ControleAluno();
         //controle.verificaCadastro();
         controle.habilitaButtonAluno();
         
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAlunoActionPerformed

    private void jBgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgradeActionPerformed
   jBgrade.setEnabled(false);
        
        
        
    }//GEN-LAST:event_jBgradeActionPerformed

    private void jBDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDisciplinasActionPerformed
        // TODO add your handling code here:
       InListDisciplines disciplinas= new InListDisciplines();
        disciplinas.setVisible(true);
        
        
    }//GEN-LAST:event_jBDisciplinasActionPerformed

    private  void HabilitaPrincipal(){
        boolean op = true ;
        while (op){
        jBAluno.setEnabled(false);
        jBgrade.setEnabled(false);
        jBDisciplinas.setEnabled(false);
        jBVisualizaGrade.setEnabled(false);
        }
    }
    
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAluno;
    private javax.swing.JButton jBDisciplinas;
    private javax.swing.JButton jBVisualizaGrade;
    private javax.swing.JButton jBgrade;
    private javax.swing.JButton jBpdf;
    private javax.swing.JLabel jLUnBimg;
    private javax.swing.JLabel jLUniversidadeBrasilia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
